added README.md file for day1 of terraform
techslateramu/allinone pull request #66
Opened 2023-12-21 17:15 UTC by harshini6395

added README.md file for day1 of terraform

2023-12-21 17:53 UTC, DivyaMandati commented on terraform/day1/README.md
> +![TechSlate](../global/images/ts.png)
image is not visible please have a look again

2023-12-21 17:55 UTC, DivyaMandati commented on terraform/day1/README.md
> +- A resource group is a logical container used in cloud computing environments to organize and manage related resources. It is a fundamental concept in cloud platforms such as Microsoft Azure, Amazon
as resource group is in azure so keep it as just azue dont include aws and gcp write defination more clearly

2023-12-21 17:55 UTC, DivyaMandati commented on terraform/day1/README.md
> +- A storage account is a fundamental construct in cloud computing platforms like Microsoft Azure, Amazon Web Services (AWS), and Google Cloud Platform (GCP). It serves as a logical container for stor
same goes here aswell remove aws,gcp and give defination of azure storage account

2023-12-21 17:56 UTC, DivyaMandati commented on terraform/day1/README.md
> +- The use of locals.tf helps to keep your main configuration cleaner and more focused on resource definitions, while complex expressions or computations are encapsulated in the locals block. It also
give more detail defination of locals which is used to give proper naming convention for resourses

2023-12-21 17:57 UTC, DivyaMandati reviewed
address the comments

2023-12-22 05:56 UTC, lavanyanaidu999 commented on terraform/day1/README.md
> +
let it be variables.. instead of variables. tf...
The question can be -----------> **What are variables in Terraform ?**

2023-12-22 05:57 UTC, lavanyanaidu999 commented on terraform/day1/README.md
> +## What is locals.tf file?
same goes here for locals as well.

2023-12-22 05:57 UTC, lavanyanaidu999 commented on terraform/day1/README.md
> +## What is outputs.tf file?
here for outputs as well!

2023-12-22 05:58 UTC, lavanyanaidu999 commented on terraform/day1/README.md
> +- In Terraform, an outputs.tf file is used to define output values that are exposed to users or other Terraform configurations when they consume your module. Outputs provide a way to share informatio
the answer should not be like --->
- In Terraform, an outputs.tf file is used  to

it can be like -----> In terraform outputs are used to

2023-12-22 05:59 UTC, lavanyanaidu999 requested changes
please consider the comments and raise PR

2023-12-22 06:29 UTC, lavanyanaidu999 commented on terraform/day1/README.md
> +- locals.tf is a Terraform configuration file where you define local values or variables to simplify and centralize expressions used in your Terraform code. This file helps improve readability, maint
change locals.tf is to locals are

2023-12-22 06:30 UTC, lavanyanaidu999 commented on terraform/day1/README.md
> +- The variables.tf file is used to declare and define variables that will be used in your Terraform configuration files (typically with a .tf extension). These variables can represent values that may
change variables.tf file is to variables are

2023-12-22 06:33 UTC, lavanyanaidu999 commented on terraform/day1/README.md
> +- In terraform outputs are used to define output values that are exposed to users or other Terraform configurations when they consume your module. Outputs provide a way to share information about the
In terraform outputs are --> wrong sentence

change it to -----> outputs in terraform are

2023-12-22 06:33 UTC, lavanyanaidu999 requested changes
please make changes

2023-12-22 06:44 UTC, lavanyanaidu999 approved these changes

2023-12-22 09:25 UTC, techslateramu approved these changes

2023-12-22 09:25 UTC, techslateramu commented
Good Job Harshni !

2023-12-22 09:25 UTC, merged